### ISSUE TITLE
Strange result

### ISSUE THREAD

**Issue by iroQuai** [mendhak/waveshare-epaper-display#2]
Followed your instructions. Script works, but gives a different result than I'd expected!

Example: 
Http://imgur.com/a/nrQgNok

**Comment by mendhak** [comment]
I wonder why the train templates are just being written instead of hidden. 

In your `.svg` can you look for the train summary bits, and just remove them. 

![image](https://user-images.githubusercontent.com/746276/72223491-4abc9d00-3567-11ea-8a14-6658fbbdd54a.png)


Also in the `run.sh`, just get rid of the condition

```bash
if (( $current_hour >= 7 )) && (( $current_hour <= 9 )); then
    figlet Pihole info
    sudo -E python3 screen-pihole-get.py hide
    
    figlet Train summary
    sudo -E python3 screen-traintimes-get.py show
else
    figlet Pihole info
    sudo -E python3 screen-pihole-get.py show
    
    figlet Train summary
    sudo -E python3 screen-traintimes-get.py hide
fi

```

should become

```bash
    figlet Pihole info
    sudo -E python3 screen-pihole-get.py show
 
```
